image: docker:stable

services:
  - docker:dind

stages:
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login --password $CI_REGISTRY_PASSWORD --username $CI_REGISTRY_USER $CI_REGISTRY

deploy:
  stage: deploy
  script:
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - wget -q --post-data="" -O /dev/null $PORTAINER_WEBHOOK_URL || true
  only:
    - master